services:
  - type: web
    name: grouphelper-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python OGbotas.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: NOWPAYMENTS_API_KEY
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DATA_DIR
        value: /opt/render/data

